// ── 한글 라벨 매핑 (단일 소스) ──
// page.tsx 와 EventLog.tsx 가 각자 들고 있던 라벨 표를 여기로 통합한다.
// 두 곳에 흩어져 있던 TOOL_LABELS 가 서로 어긋나 있었으므로(예: class_seating·poll
// 누락) 두 정의의 합집합을 단일 소스로 유지한다.

export const TOOL_LABELS: Record<string, string> = {
  timer: '타이머',
  random_picker: '랜덤뽑기',
  roulette: '룰렛',
  scoreboard: '점수판',
  traffic_light: '신호등',
  dice: '주사위',
  coin: '동전던지기',
  qr: 'QR코드',
  activity_symbol: '활동기호',
  vote: '투표',
  survey: '설문조사',
  wordcloud: '워드클라우드',
  seat_picker: '자리뽑기',
  assignment: '과제수합',
  class_seating: '자리배치',
  poll: '투표',
};

export const EVENT_LABELS: Record<string, string> = {
  app_open: '앱 열기',
  app_close: '앱 종료',
  page_view: '페이지 이동',
  widget_open: '위젯 열기',
  widget_close: '위젯 닫기',
  timetable_edit: '시간표 수정',
  seating_shuffle: '좌석 섞기',
  seating_drag: '좌석 드래그',
  event_create: '일정 생성',
  memo_create: '메모 생성',
  todo_toggle: '할일 체크',
  tool_use: '도구 사용',
  export: '내보내기',
  share_import: '공유 가져오기',
  chatbot_open: '챗봇 열기',
  chatbot_message: '챗봇 메시지',
  update_installed: '업데이트 설치',
  onboarding_complete: '온보딩 완료',
  school_set: '학교 설정',
  class_set: '학급 설정',
  error: '에러',
  feature_discovery: '기능 발견',
  session_start: '세션 시작',
  assignment_create: '과제 생성',
  assignment_share: '과제 공유',
  assignment_view: '과제 조회',
  consultation_create: '상담 생성',
  consultation_update: '상담 수정',
  bookmark_add: '즐겨찾기 추가',
  bookmark_click: '즐겨찾기 클릭',
  feedback_submit: '피드백 제출',
  settings_change: '설정 변경',
  timetable_neis_sync: 'NEIS 동기화',
  widget_layout_change: '위젯 레이아웃 변경',
  onboarding_roles_selected: '역할 선택',
  onboarding_widget_preset: '위젯 프리셋 선택',
  chatbot_feedback: '챗봇 피드백',
  chatbot_escalate: '챗봇 에스컬레이션',
  share_modal_open: '공유 모달 열기',
  share_click: '공유 클릭',
  share_prompt_shown: '공유 안내 표시',
  share_prompt_action: '공유 안내 응답',
};

export const PAGE_LABELS: Record<string, string> = {
  dashboard: '대시보드',
  timetable: '시간표',
  seating: '좌석배치',
  schedule: '일정관리',
  'student-records': '담임메모',
  memo: '메모',
  todo: '할일',
  settings: '설정',
  tools: '도구함',
  'class-management': '수업관리',
  'tool-timer': '타이머',
  'tool-random-picker': '랜덤뽑기',
  'tool-roulette': '룰렛',
  'tool-scoreboard': '점수판',
  'tool-traffic-light': '신호등',
  'tool-dice': '주사위',
  'tool-coin': '동전던지기',
  'tool-qr': 'QR코드',
  'tool-work-symbols': '활동기호',
  'tool-vote': '투표',
  'tool-survey': '설문조사',
  'tool-wordcloud': '워드클라우드',
  'tool-seat-picker': '자리뽑기',
  'tool-poll': '투표',
  'tool-assignment': '과제',
  'tool-class-seating': '자리배치',
  bookmarks: '즐겨찾기',
};
